package com.lexease.shared.audit;

public enum AuditAction {
    AUTHOR_CREATED,
    AUTHOR_DELETED,
    AUTHOR_UPDATED,
    DISPLAY_SETTINGS_RESET,
    DISPLAY_SETTINGS_SAVED,
    GENRE_CREATED,
    GENRE_DELETED,
    GENRE_UPDATED,
    GUARDIAN_CHILD_LINK_ACCEPTED,
    GUARDIAN_CHILD_LINK_REJECTED,
    GUARDIAN_CHILD_LINK_REQUESTED,
    GUARDIAN_CHILD_LINK_REVOKED,
    REFRESH_TOKEN_ROTATED,
    STORY_ARCHIVED,
    STORY_BLOCKED,
    STORY_CREATED,
    STORY_UNBLOCKED,
    STORY_UPDATED,
    USER_LOGIN,
    USER_REGISTERED
}
