package com.lexease.shared.audit;

public enum AuditAction {
    GUARDIAN_CHILD_LINK_ACCEPTED,
    GUARDIAN_CHILD_LINK_REJECTED,
    GUARDIAN_CHILD_LINK_REQUESTED,
    GUARDIAN_CHILD_LINK_REVOKED,
    REFRESH_TOKEN_ROTATED,
    USER_LOGIN,
    USER_REGISTERED
}
