package com.lexease.shared.api;

public enum ErrorCode {
    ADMIN_REGISTER_DISABLED,
    CHILD_NOT_FOUND,
    EMAIL_ALREADY_REGISTERED,
    FORBIDDEN,
    INVALID_ACCESS_TOKEN,
    INVALID_CHILD,
    INVALID_CREDENTIALS,
    INVALID_LINK,
    INVALID_REFRESH_TOKEN,
    LINK_ACCEPT_FORBIDDEN,
    LINK_ALREADY_EXISTS,
    LINK_NOT_FOUND,
    LINK_NOT_PENDING,
    LINK_REJECT_FORBIDDEN,
    LINK_REVOKE_FORBIDDEN,
    TOKEN_EXPIRED,
    UNAUTHORIZED,
    USER_DISABLED,
    USER_NOT_FOUND,
    VALIDATION_ERROR
}
